### ISSUE TITLE
wrong intensity of diffraction

### ISSUE THREAD

**Issue by hk80s** [aripekka/pyTTE#7]
While using following syntex 
N = 256
angle = (py.asarray(range(N))-N//2)
ka1_energy = 8.04778
ka2_energy = 8.02783
thickness = 100
R_bend = 1
nu = 0.25
ujac= tt.deformation.isotropic_plate(R_bend,-R_bend/nu,nu,thickness*1e-6)
ka1_diffraction,t = tt.takagitaupin(scantype='angle',\
                                    scan=angle,\
                                    constant=ka1_energy,\
                                    polarization ='pi',\
                                    crystal_str = 'InAs', \
                                    hkl=[1,1,1], \
                                    asymmetry=0,\
                                    thickness=thickness,\
                                    debyeWaller=1,displacement_jacobian=ujac)
under this condition the diffracted intensity is OK. 
But as we started to increase the thickness the integration started to abruptly stop. For example at 275 micron it stops at the tail of falling edge, at 290 micron it is near the peak as we increase thickness this started to fail  even earlier.
Please give some feedback. I am trying to write a paper using this code I have followed your recent publication in JAC 2016. I have also found that in gronowaski 1991 the factor epsilon=zeta1-AB is actually epsilon = zeta2-AB. I hope you have already corrected this or not using from there.

**Comment by aripekka** [comment]
Thanks for the report. I looked in to the matter and managed to recreate the problem.

In the end this is an inherent problem with the Takagi-Taupin equations, which are numerically very difficult to solve. The derivative becomes very large far away from the exact Laue condition which causes problems with bent crystals where the Laue condition changes as a function of position due to deformation, especially at low Bragg angles. I am aware that there are errors in Gronkowski but the equations used in PyTTE are derived independently.

There are a couple of solutions though. You can try the 1.0 alpha version of the code which is numerically more stable than this 0.1.11. However, the api is completely different. Here's how to calculate your example code with it:
```
import numpy as np
import matplotlib.pyplot as plt
from pyTTE_alpha import TakagiTaupin, TTcrystal, TTscan,Quantity

crystal = 'InAs'
hkl = [1,1,1]
R_bend = Quantity(1,'m')
nu = 0.25
E = Quantity(160,'GPa') #This is Young's modulus. It's value does not matter as it is not used in this calculatino
thickness = Quantity(290,'um')
polarization = 'pi'
scan = Quantity(np.linspace(-25,75,200),'arcsec')
energy = Quantity(8.04778,'keV')

ttx = TTcrystal(crystal=crystal, hkl=hkl, thickness=thickness, Rx = R_bend , Ry= -R_bend/nu, E = E, nu = nu)
tts = TTscan(scan = scan, constant = energy, polarization = polarization)
tt = TakagiTaupin(ttx,tts)

scan_vector, diffraction, forward_diffraction = tt.run()
```

However, also the new code breaks down after 350 um. Fortunately, the beam does not penetrate very deep into the crystal with low Bragg angles, so you don't have to solve the TT-equation starting from the bottom. Instead, you can use smaller crystal `thickness` in simulation, but modify `deformation.isotropic_plate` to include an offset to z, so that the function returns the deformation in z = [0, -`thickness`] of a much thicker crystal. Alternatively, you can edit the starting point of the integration in the main code `res=r.integrate(-thickness)` -> `res=r.integrate(-new_start_point)`.

For further questions on this matter, please contact me by mail (honkanen.ap@gmail.com).
